code/src/main/java/cs544/project/onlineshoppingstore/model/Order.java
package cs544.project.onlineshoppingstore.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "BookOrder")
public class Order {

	@Id @GeneratedValue
	private long id;
	
	@Temporal(TemporalType.TIMESTAMP)
	@NotNull(message = "Order date cannot be blank.")
	private Date orderDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@NotNull(message = "Delivery date cannot be blank.")
	private Date delivaryDate;
	
	@Enumerated(EnumType.STRING)
	private OrderStatus orderStatus;
	
	@NotNull(message = "Total cost cannot be blank.")
	private double total;
	
	@NotNull(message = "Total Quantity cannot be blank.")
	private int totalQuantity;
	
	@OneToMany(mappedBy = "order")
	private List<Orderline> orderlines = new ArrayList<>();
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customerId")
	private Customer customer;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}


	public Date getOrderDate() {
		return orderDate;
	}


	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}


	public Date getDelivaryDate() {
		return delivaryDate;
	}


	public void setDelivaryDate(Date delivaryDate) {
		this.delivaryDate = delivaryDate;
	}


	public OrderStatus getOrderStatus() {
		return orderStatus;
	}


	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}


	public double getTotal() {
		return total;
	}


	public void setTotal(double total) {
		this.total = total;
	}


	public int getTotalQuantity() {
		return totalQuantity;
	}


	public void setTotalQuantity(int totalQuantity) {
		this.totalQuantity = totalQuantity;
	}


	public List<Orderline> getOrderlines() {
		return orderlines;
	}


	public void setOrderlines(List<Orderline> orderlines) {
		this.orderlines = orderlines;
	}


	public Customer getCustomer() {
		return customer;
	}


	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	
	
	public String getOrderLinesDetail(){
		String orderlines = "";
	for(Orderline ol: this.orderlines){
			orderlines += ol.getBook().getTitle() + " <b> BY </b> " + ol.getBook().getAuthorName()  + " ";
		}
		return orderlines;
	}
	
}

code/src/main/java/cs544/project/onlineshoppingstore/controller/OrderController.java
package cs544.project.onlineshoppingstore.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import cs544.project.onlineshoppingstore.model.Customer;
import cs544.project.onlineshoppingstore.model.Order;
import cs544.project.onlineshoppingstore.service.CustomerService;
import cs544.project.onlineshoppingstore.service.OrderService;

@Controller
public class OrderController {

	@Autowired
	private OrderService orderService;
	
	@Autowired
	private CustomerService customerService;

	
	@RequestMapping(value = "/order/orderhistory", method = RequestMethod.GET)
	public String viewOrderHistory( Model model){
		
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		String username = authentication.getName();
		long id = customerService.findByUsername(username).getId();
		
		Customer customer = customerService.get(id);
		List<Order> orders = customer.getOrder();
	    System.out.println("Number of orders " + orders.size());
		model.addAttribute("orders", orders);
	
		return "order/orderHistory";
	}
}

code/src/main/webapp/WEB-INF/views/order/orderHistory.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Customer History | AJM-Online Book Store</title>
<style type="text/css">
.navbar {
	margin-bottom: 0px;
}
</style>

</head>
<body>

	<div class="container">
		<div class="page-header ">
			<h3>Order History</h3>
		</div>
		
		<br />

		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Books</th>
						<th>Total Cost</th>
						<th>Order Date</th>
						<th>Delivery Date</th>
						<th>Status</th>
					</tr>
				</thead>
				
				<c:forEach var="order" items="${orders}">
					<tr>
						<td>${order.orderLinesDetail}</td>
						<td>${order.total}</td>
						<td>${order.orderDate}</td>
						<td><fmt:formatDate value="${order.delivaryDate}" var="formattedDate" 
                type="date" pattern="MMM-dd-yyyy" /> ${formattedDate}</td>
                
                <td>${order.orderStatus }</td>
					</tr>
				</c:forEach>
			</table>
		</div>
	</div>
</body>
</html>